# Vitenskapsfilosofi

# 1.0: Oppgåve 1: David Hume og Induksjonisme

Innanfor den vitskapelege metoden finner ein to motsetningar, dette dei to metodane induksjon og deduksjon. Induksjon som ein vitskapeleg metode som tar utgangspunkt i enkelte individuelle utsegn og erfaringar. Med bakgrunn i dette ynskjer å komme fram til meir omfattande lovar og utsegn (Tranøy, 2021). Sjølv om induksjon er ein anerkjent metode innanfor vitskapeleg metode og filosofi så stilles det spørsmål med denne metoden. Ein av dei som har fleire meiningar rundt dette, er den skotske filosofen David Hume. Sentralt i hans arbeidet er induksjon, og spørsmålet rundt bruken av induksjon i vitenskap(Alnes, 2022**)**  

Humes skepsis til induksjon har sitt utspring i tanken om det å kunne skape ein generell oppfatning av det som me allereie veit eller endå ikkje veit heilt sikker. For det er slik at den generelle oppfatninga har blitt slik på grunn at det ikkje er blitt oppservert ein motsetning til denne oppfatninga. Så inntil me observere ein slik oppfatning, vil dette være den oppfatninga som står sterkast. Hume tenkjer at det ikkje er rasjonelt å argumentere for noko, viss me ikkje er sikker på at me ein gang kan observere noko anna. Altså viss me ikkje er sikker på at me skal kunne observere noko anna, så skal me likevel meine dette(Holmen, 2023). Det er dette som blir beskrive som uniformitetsprinsippet, som me enkelt kan beskrive ut i frå at framtida vil være lik fortida. I litteraturen blir dyr brukt i fleire eksempel for å vise Humes tankegang. For kan me sei at det er ein spesiell farge som gjelder for det dyre, berre på bakgrunn av observasjonane me har gjort og dermed gjere dette til den meir generelle haldninga for dette? Hume meiner i dette tilfellet at det er sannsynligheten som slår inn, for viss me ikkje har gjort andre observasjonar så vill sannsynligheten være liten for at me finner noko anna. Dermed har me skapt kjernen av induksjonsproblemet, for korleis skal me kunne sei noko om dette uten av referere til korleis det har vert før og uniformitetsprinsippet ? Men då er me tilbake til at me generalisere igjen, for då vill me sei at det generelt har gått fint tidlegare. Dermed har me argument som går rundt og rundt i ein sirkel. Det er her Hume finner problem med induksjon som metode. Sjølv om Humes argument kan angå veldig mykje vitenskap, sidan mykje av det som me tar for oss går på det med observasjonar(Holmen, 2023).

Me har fleire ulike former for vitenskap, ein av desse er formalvitskap som er eit felt der det er svært vanskeleg å motbevisa Hume sitt uniformitetsprinsipp. Denne tar for seg blant anna matematikken dreier det seg ikkje i like stor grad om observasjonar. Det er ikkje meir enn et svar på 1+1=2, sidan me her har med konstante variablar som ikkje er mogeleg å endre. I motsetting til eksempla som er gitt tidlegare med dyrs farge. Der me veit at det finnes ein stor grad av påverking, som igjen er vanskeleg å ha ein sikker observasjon av.

# 2.0: Oppgåve 2: Falsifikasjonisme

Me kan beskrive falsifikasjonisme som «en påvising av at en teori/hypotese eller påstand» er gal eller uhaldbare. Denne teorien har sitt utspring frå mange av de store teorien på tideleg 1900 talet, som kunne finne svar på sin teori uansett korleis ein vridde og vente på de(Popper, 1985).  Falsifikasjonisme er då det motsette av verifikasjon, som er den vanlegaste måten å jobbe på i dagens vitenskap. Der ein ynskjer å finne fram til om ein hypotese er (Verifikasjon, 2021). Men kva vill dette faktisk sei? Den anerkjente filosofen Karl Popper har lenge vert ein av dei viktigaste personane innanfor dette feltet. Han meiner at det ligger en viktig skilnad mellom falsifikasjonisme og verifikasjon, når me skal svare på ein hypotese om generelle utsegn eller det som blir beskrive som naturlover. Dette til tross for at ein kan finne ein logisk forklaring på at dette ikkje stemmer. Men kva er så hensiktene til falsifikasjonisme? For deira del blir det då viktig å auke den generelle graden av falsefiserbare hypotesar. Dette vil då sei at ein skal jobbe fram hypotesar som, uansett korleis du vri og vender på det kan motbevises(Alnes,2021).

Så kva er då ein hypotese som, Popper og hans falsifikasjonisme ville kunne stille eit spørsmål med? Etter å ha jobba mange år som skitrenar og no som masterstudent innanfor treningsfysiologi, tenkjer eg at falsifikasjonsme er noko ein skal være svært oppmerksam på. For det er ikkje slik at all framgang som ein finner i eit testlaboratorium kan gjenskapast i praksis utanfor testlaboratoriet. Forskinga innanfor idrett dreier seg i stor grad om å finne måtar å forbetre faktorar som har ein betydning for prestasjonen i gitte idrettar. For å bruke langrenn som er min idrett som eit eksempel og dermed kan bruke eigene erfaringar innanfor dette emnet. Tre av mine utøvarar var med på ein studie for å sjå om ein spesiell måte å gjennomføre høgintensiv trening(H0) ville ha ein betre effekt enn normal gjennomføring(H1). Ved post test viste det seg at H0 stemte både for den individuelle utøver og gjennom statistiske testar som var gjennomført på resultata til alle deltakarane. Studien var gjennomført i sin heilheit i eit testlaboratorium, for å kunne sikre ein god reliabilitet i studien. Men sikra dette ein gode falsefiserbarheit i studien? Etter å ha gjennomført studien, såg me dette som ein moglegheit til å gjennomføre denne type treninga på ein ny måte og som vill være med på gje utøvarane eit ekstra løft på ein viktig prestasjonsvariabel. Men etter alle mine år som trener blei dette den viktigaste erfaring eg har på forskjell mellom teori og praksis, og grad av falsefiserbarheit. For den praktiske gjennomføringa viste seg å ikkje lykkes på same måte, som med den opprinnelige studien. Når me gjennomførte dette ute og tok vekk dei verktøya ein har inne i ein labb for å kunne gjere dette reliabilitet, så blei det ein lav grad av falsefiserbarheit. For det ende med at mange av utøvarane sjuke, eller opplevde ikkje den ønska effekten i ettertid. I seinare tid er det berre ein av utøvarane som har prøvd denne forma for trening igjen. [\[Pm1\]](#_msocom_1) Dette er ikkje eit problem som gjelder for denne spesifikke studien, men i hovudsak der ein i det daglege etter ein studie. Dermed er det i mange idrettar stor forskjell mellom det som blir gjort i forskinga og praksis.

Eg trur eit slikt problem er mogeleg å løyse, men då må det gå på bekostning av andre faktorar. Ein må også kunne forske på korleis ein skal klare å omsette trening som blir gjort i kontrollerte forhold om til praktisk gjennomføring. Dermed må ein være villig til å kunne å ofre reliabiliteten i et prosjekt, og heller fokusere på kva som skal til for å få denne spesifikke metoden til å bli den nye praksisen. Dermed er ein inne på eit nytt problem, som igjen vill være problematisk for eit anna viktig prinsipp i det å sikre ein god vitenskap.

 [\[Pm1\]](#_msoanchor_1)Dette er et interessant eksempel, men det ser ut til å være et eksempel på falsifisering! Hypotesen fra labben ble falsifisert i mer realistiske omgivelser.
