# Studiedesign

I dette arbeidskravet skal vi se på hvordan ulike studier har blitt designet og hvordan de har gjennomført sitt studiedesign og hva statistiske analyser de har gjennomført. Jeg har valgt å ta utgangspunkt i fem studier som omhandler blokk periodisering av utholdenhetstrening. Studiene er @br_ronnestad_effects_2012, @ronnestad_block_2014, @fabio_a_breil_block_2010, @garcia-pallares_performance_2010, @guro_strom_solli_block_2019

Fellestrekket for disse studiene er at alle er gjort på en gruppe utøvere som holder svært høyt nivå innenfor sine idretter. @garcia-pallares_performance_2010 og @guro_strom_solli_block_2019 bruker utøvere som er i den absolutte verdenstoppen innen for sine idretter. Men hva er blokk periodisering av utholdenhetstrening? Vi kan definert som en type modell for trening, der en dele det opp i kortere perioder (1-4 uker). I disse kortere periodene vill en ha fokus på å forbedre en spesifikk egenskap, som for eksempel VO$_{2maks}$. Før en da kan i neste periode ha et større fokus på en annen faktor som er med på påvirker prestasjonen i den gitte idretten [@br_ronnestad_effects_2012].

## Studienes spørsmål

Dette er 5 studier som tar for det samme treningsprinsippet, men som har blitt gjennomført på forskjellig måte. Alle studiene har til felles at de ønsker å se på om det har vert eller en kan skape en forbedring ved å organisere trening som en blokk periodisering en det som en kan kategorisere som normal måte å gjennomføre utholdenhetstrening. I @br_ronnestad_effects_2012 og @ronnestad_block_2014 blir denne tradisjonelle formen (TRAD) for utholdenhets trening beskrevet som to høy intensive økter i løpet av en trenings uke. Utover dette fyller en gjerne på med rolig trening. Alle studiene har som vi skal se på i denne oppgaven stiller sei spørsmålet om en BP kan forbedre faktorer som er avgjørende for prestasjonen i utholdenhetsidrett.

## Studiedesign

Innen for forskingen på idrett og de ulike variablene som skal til for å prestere i idrett. Så er det en type studie som er det vanligste typen å bruke, dette er det som blir referert til som *case-kontroll studier.* Dette er studier som er bygd opp med en case gruppe, som i idrettstudier skal gjennomføre en ny form for trening. Disse trenings dataene blir sammenlignet opp mot kontroll gruppen, som i dette tilfellet har forsatt med sin vanlige tradisjonelle trening. Så vill disse to gruppene målt opp mot hverandre, for å sjå om det er en bedre framgang i enten case gruppa eller i kontroll gruppa[@browner2023]. I vårt utvalg av studier har vi i stor grad studier som blir gjennomført på denne måten, der du har en case gruppe, som i dette tilfellet vil være en blok periodisering gruppe(BP). Mens en vill ha en kontroll gruppe, som i disse tilfellene forsetter med tradisjonell utholdenhetstrening(TRAD). @br_ronnestad_effects_2012 og @ronnestad_block_2014 er studier satt opp etter denne formen for studiedesign. @fabio_a_breil_block_2010 har det samme oppsettet, men den skiller seg like vell fra @br_ronnestad_effects_2012 og @ronnestad_block_2014. I @br_ronnestad_effects_2012 og @ronnestad_block_2014 så er det et oppsett der en skal ha et like stort trenings volum i TRAD og BP. Dette vill si at når en teller opp skal en ha like mange høy intensive økter(HIT) i både TRAD og BP. Den eneste forskjellen er hvordan en plassere disse øktene i forhold til hverandre. Mens @fabio_a_breil_block_2010 er der en gruppe gjennomfører en BP. Men i motsetning til @br_ronnestad_effects_2012 og så er det stor forskjell til TRAD gruppen. Da denne gruppen forsette å trene som normalt, gjør dette at det sammenhengende treningtingstimuli blir veldig forskjellig.

Selv om @garcia-pallares_performance_2010 også er en"case-kontroll studie", så skiller deg sei fra de andre med at den bruke de samme 10 utøvere både i som case-gruppe men også som kontroll gruppe. Der @rønnestad2014, @b.r.rønnestad2012 og @fabioa.breil2010 bruker forskjellige utøvere i case gruppen og i kontroll bruker. Noe som vi kan se på som både en styrke og en svakhet, for med å bruke de samme personene til å teste ut to forskjellige treningsformer vill en få et godt svar på hva metode fungere best for de ulike personene. Men den foregår også over to år, noe som ikke sikrer oss for om det ene treningsåret ikke har innvirkning på den andre treningsåret. Men dette er en studie som virkelig er spesiell i sammenligning med andre studier. Den gjennomføres over 2 år, også i forbindelse med oppkjøringen til flere internasjonale mesterskap. Der en har utøvere har utøvere av høy internasjonal klasse, som skal være med å kjempe helt i toppen i disse konkurnasene. Noe som gjør denne studien unikt etter min mening, at en klarer å endre såpass mye på treningen til disse utøverne. @guro_strom_solli_block_2019 gjennomfører en case studie av den mest vinnende langrennsløper, med et utgangspunkt i et systematisk gjennomgang av hennes treningdagbøker. Studien bruker to trenings år som utgangspunkt. Et som ble gjennomført med TRAD og et som blei gjennomført med BP. **Eventuelt finne ein referanse på case studie**

Selv om det er litt forskjell i disse studiene så har alle en trenings intervensjon i studiene sine, men trenings intervensjonen er også gjort på en svært forskjellig måte. @ronnestad_block_2014 og @br_ronnestad_effects_2012 inneholder trenings intervensjonen et like stort volum, men det en vesentlig forskjell i organiseringen. No som gir oss et godt utgangspunkt for å sjå på forskjellene. @fabio_a_breil_block_2010 er som tidligere beskrevet også enn RBT studie som @ronnestad_block_2014 og @br_ronnestad_effects_2012 . Men de skiller sei litt fra @br_ronnestad_effects_2012 og @ronnestad_block_2014 , med at det er en stor forskjell i trening til kontrollgruppen. I @fabio_a_breil_block_2010 så har en ikke lagt like stor vekt på å ha et likt trenings volum i de to gruppene. Det er også en stor forskjell i type trening som ble gjort i de to studiene, noe som er en relativ stor feilkilde. Men på bakgrunn av at @guro_strom_solli_block_2019 har en case studie, så vill deres trenings intervensjon være svært forskjellig fra de andre studiene. Det er også det som er det store spørsmålet ved denne studien, er at det er 10 år mellom de to treningsåra som blir sammenlignet. For med 10 år kommer det også en stor andel annen trening inn i bilde. En vanlig treningsmengde for en langrennsløper vill være i område av 750 til 800 timer med utholdenhetstrening\[ @guro_strom_solli_block_2019\] . Når vi da ser at det er 10 år mellom disse to treningsårene, utgjør dette en vesentlig stor treningsmengde som vill ha påvirkning på utøverens fysiske form. @garcia-pallares_performance_2010 gjennomfører treningen over en tidsperiode på to år. Denne perioden starta med et år med et år med TRAD, for så å gjennomføre BP i et år. I motsetning til @br_ronnestad_effects_2012 og @ronnestad_block_2014 så ble det i denne studien en forskjell i mengden trening i året en gjennomført TRAD og BP. En viktig punkt i treninga i denne studien er at i en overgang mellom de to sesongene ble det en periode på 5 uker der en hadde "overgangsmtrening" som var mer fritt og ikke skulle påvirke i den ene eller andre retningen.

### Statistikk

Det statistiske arbeidet både før, under og etter studiene er gjort på samme måte. De blei ikke i noen av studiene gjort en kalkulering av statistisk power på forhånd. Alle studiene brukte et signifikant nivå på 0,05, for å kunne avgjøre forskjellene mellom de to gruppene som gjennomførte TRAD og BP. **I @ronnestad_block_2014 og @br_ronnestad_effects_2012** gjort kalkulering av "Cohen´s d" å kalkulere. Dette er et mål på effektstørrelsen i utvalget som er tatt ut av populasjonen. Ved utrekning av "Cohen´s d" vill en få et resultat som ligger innenfor de følgende områdene triviell 0.0 til 0.2, liten 0.2 til 0.6, moderat 0.6 til 1.2, stor 1.2 til 2.0 og veldig stor \>2.0 [@hopkins_progressive_2009].

Dette vart også gjort på bakgrunn i de allerede små gruppe størrelsene og godt trente utøvere. Der det er unaturlig å forvente de aller største forbedringene. Med et testbatteri i flere av studiene som inkluderte flere variabler, er det ikke alle vi ser en signifikant forbedring på alle variabler. Studiene er her flink til å påpeke at det er ulike faktorer for prestasjon som ikke vill bli forbedret, men det er andres som vil bli forbedret. Dette blir brukt også i studienes konklusjon, da dette er viktige faktorer som vil ha noe å si for hvordan en anvender en slik studie i trenings planen til en utøver. Som det blir understrek i @fabio_a_breil_block_2010 sin konklusjon, som er den studien med et av de største testbatteriene. De finner en klar effekt av det å BP utholdenhetstreningen, men siden dette går på bekostning av andre viktige faktorer SMJ og CJ så krever det veldig god planlegging for at en skal kunne opprettholde alle de viktige prestasjons variablene. @garcia-pallares_performance_2010 bruker to andre statistiske tester enn hva som blir gjort i de andre. Dette er *The Shapiro-Wilk test* og *Mann - Whitney U* i sine analyser, som to tester som ser på normaliteten i de to gruppene. En Shapiro-Wilk test, er en statistisk test som skiller seg fra den normale t-testen, da denne ikke tar utgangspunkt i at det er en normalfordeling på observasjonene i et utvalg. Altså er dette en test som passer når en forventer at observasjonen ikke vil fordele sei etter en normalkurve[@r.dudley2012] Som i tilfellet til @garcia-pallares_performance_2010, der en har forsøkspersoner som er blant de absolutte beste i verden på det de driver med og dermed ikke passer innenfor normalfordelingen. *Mann - Whitney U* som er den andre testen som blir brukt til å sammenligne om det er forskjell i den avhengige variabelen for BP gruppen og for TRAD gruppen. Den ser på om fordelingen av denne avhengige variabelen er lik for begge gruppe og kan derfor komme fra samme populasjon[@karadimitriou_sofia_maria_mann-whitney_2018].

### Forsøkspersoner

Dette er fem studier som alle har det tilfelles at det er gjort på godt trente personer eller bedre. @garcia-pallares_performance_2010 og @guro_strom_solli_block_2019 er studier som å gjort på utøvere som har prestert på topp internasjonalt nivå.

Alle studiene ble gjort på en treningsgruppe, som er tilknyttet enten en skole eller landslag. Det ble ikke gått ut å gjort en bredd rekruttering i den brede befolkningen. I @ronnestad_block_2014 og @br_ronnestad_effects_2012 blir de referert til studien av @jeukendrup_bioenergetics_2000 for å kategorisere nivået til syklister. Ut i fra hans karakteristikker så er det ikke så mange personer som kan passe disse kategoriene viss enn ønsker å gjennomføre forsking for å finne nye måter å forbedre prestasjonen til utøvere som skal prestere på topp nivå. Dermed kan vi betrakte at dette er studier som er gjort på små populasjoner og en dertil mindre utvalg fra denne populasjonen. Vi kan dermed si at dette skaper en del statistiske svakheter i forhold til antallet forsøkspersoner.

### Testing

De fleste studier har en pre test og en post test i av disse utvalgte studiene. Selv om de gjør denne testingen på ulik måte. Det skilles litt i hva andre variabler som blir brukt, men det er laktatprofil og VO$_{2maks}$ er en viktig variabel for å måle forskjellen mellom BP og TRAD. Enkelte studier som @fabio_a_breil_block_2010 og @garcia-pallares_performance_2010 har også valgt å inkludere andre spesifikke tester for den spesifikke idretten i sitt testbatteri. I @fabio_a_breil_block_2010 er dette tester som for eksempel counter-movement jump(CMJ) og squat jumps(SJ) på kraft plattform. Dette er variabler som er viktig for prestasjonen i alpint. Siden @guro_strom_solli_block_2019 er en case studie som er gjort lenge etter at disse sesongene ble gjennomført, så gjennomførere disse ikke noe testing. No som gjør at vi ikke ser noe utvikling i de variablene som er viktig for prestasjon, og som vil kunne være viktig for å sjå på hva effekt de ulike treningsformene ga på denne utøveren.

### Resultat

Så hva seier resultatene i disse fem studiene, som alle tar for seg BP vs. TRAD? Til tross for noe ulikhet i gjennomføringen av disse studiene, kan vi se at de er et samsvar med resultatene som fra alle fire av studiene. I @ronnestad_block_2014, @br_ronnestad_effects_2012 , @fabio_a_breil_block_2010 og @garcia-pallares_performance_2010 ser en at BP gir en bedre eller som en mer effektiv øke i viktige parameter som skal til for å prestere på et høyt nivå i utholdenhetsidretter. I resultat delen skiller @guro_strom_solli_block_2019 seg fra de andre studiene da denne ikke har gjennomført en testing i samme grad, og heller bruker talle fra utøveren treningsdagbok som resultat. For å se var som fungerte best, brukes også rangering ut i fra konkurranser blir brukt resultat av de to ulike årene. Dette kan stilles spørsmål med da dette ikke viser noe forbedring i en prestasjons variabel men det samla resultatet av flere. Vi også at fokuset på BP av utholdenhets variabel gir et god forbedring for denne variabel en ønsker å forbedre, men vi ser at det ikke er like positivt for andre variabler. For eksempel var det en signifikant reduksjon i maksimal kraft i CMJ og SJ [@fabio_a_breil_block_2010]

## Diskusjon

Så med utgangspunkt i disse fem studiene, hva skal vi konkludere med? Det er alle studier som gir oss et godt utgangspunkt for å kunne vurdere forskjellen mellom en TRAD grupoe eller BP. Selv om både @guro_strom_solli_block_2019 og @garcia-pallares_performance_2010 bruker samme utøvere som referanse punkt på begge metoder, og har i den form god svar på hvordan de ulike typene for trening fungere. @guro_strom_solli_block_2019 bruker to trenings år som er 10 år mellom og det som er en stor dose med trening. Vi kan ut fra studien sine beskrivelser tenke oss at denne forsøkspersonen trente mellom 750 til 850 timer i sesongen. Over 10 år tilsvare det de mellom 7500 og 8500 timer med trening. Når en har en slik dose med trening i mellom de to åra en sammenligner er det ganske klart det vill ha en form for innvirkning på den fysiske formen til forsøkspersonen i denne case studien. Mens @garcia-pallares_performance_2010 bruker 2 år etter hverandre, men her er det veldig forskjell i mengden trening som blir lagt ned i de to åra. Med at @garcía-pallarés_performance_2010 gjennomføre sin studie med påfølgende år etter hverandre er det ikke like stor forskjell i antall timer trening som er lagt ned. No som gjør at denne studien har mindre svakheter enn @gurostrømsolli2019, når det kommer til den trening forsøkspersonene har lagt ned og hva resultat som kommer ut av de. @ronnestad_block_2014 og @br_ronnestad_effects_2012 er veldig tydelig på det like trenings volumet i sine studier, gir dette oss et bedre resultat på hvordan en skal organisere trening er usikkert. Men de veier opp for at de ikke bruker de samme personene i både TRAD og BP gruppen. Dette er også to studier som har en gjennomføring av trenings delen som er mer standardisert, i form av at alle HIT økter blir gjennomført på egen sykkel på rulle. Noe som gjør at en får en veldig god gjennomføring av alle HIT øktene, med tanke på intensitetstyring. @fabio_a_breil_block_2010 har i motsetning til @ronnestad_block_2014 og @br_ronnestad_effects_2012 en kontroll gruppe som trener veldig forskjellig fra BP gruppen, som gjør at vi kan stille spørsmålet ved kontroll gruppen. Mens BP gruppen gjennomfører har et ensidig fokus på utholdenhetstrening. Så har kontrollgruppen en trening som består av utholdenhet, styrke og andre grunnleggende elementer i barmarkstrening for alpinister. Når innholdet blir så forskjellig i tillegg til mengden trening i BP og TRAD gruppa, vill en få en klar effekt på utholdenhet for BP gruppa. Men vi ser at denne effekten er positivt for utholdenhets faktorer men ikke for styrkefaktor.

Alle studiene har sine styrke og svakheter sett opp mot hverandre, men de har til felles at de har relativt få forsøkspersoner. No som gir alle studiene en viss svakhet når det kommer til statistisk styrke. Men ut i fra studiene må vi i dette tilfelle akseptere en lavere statistisk styrke for at vi skal kunne gjennomføre studier med forsøkspersoner som har de egenskapene vi er ut etter[@browner_designing_2023].

## Referanser
