project:
  type: book

book:
  title: "IDR4000-Kvantitativ metode og statistiskk"
  author: "Kandidatnummer 412"
  date: "11/15/2023"
  chapters:
    - index.qmd
    - 01-Reliabilitet.qmd
    - 02-Vitenskapsfilosofi.qmd
    - 03-Labrapport.qmd
    - 04-Studiedesign.qmd
    - 05-Repeterte forsøk.qmd
    - references.qmd

bibliography: rescorses/references.bib


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



